name: xgan
channels:
    - pytorch # for pytorch
    - conda-forge
dependencies:
    - python=3.7.3
    # base libs
    - numpy
    - matplotlib
    # DL libs
    # CUDA for Pytorch
    - cudatoolkit=9.0 # for pytorch
    - pytorch=1.1.0
    - torchvision
    # Jupyter
    - jupyter
    - jupyterlab
    # Imaging libs
    - scikit-image
    - opencv=3.4.2
    # Tools
    - tqdm
    - h5py